######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 31 16:43:25 2009
######################################################################

TEMPLATE = app
QT += webkit
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MouseCaptureWidget.h WebWindow.h
FORMS += WebWindow.ui
SOURCES += main.cpp MouseCaptureWidget.cpp WebWindow.cpp
