######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 26 12:35:31 2009
######################################################################

TEMPLATE = app
QT += webkit
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h WebWindow.h
FORMS += MainWindow.ui WebWindow.ui
SOURCES += main.cpp MainWindow.cpp WebWindow.cpp
